---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-db-dpl
spec:
  selector:
    matchLabels:
      app: unleash-db
  template:
    metadata:
      labels:
        app: unleash-db
    spec:
      containers:
        - name: unleash-db
          image: crowddotdev/db:1666904672.59dad54
          env:
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_DB
              value: crowd-unleash
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-db-svc
spec:
  type: ClusterIP
  selector:
    app: unleash-db
  ports:
    - port: 5432
      targetPort: 5432
