---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubejs-dpl
spec:
  selector:
    matchLabels:
      app: cubejs
  template:
    metadata:
      labels:
        app: cubejs
    spec:
      containers:
        - name: cubejs
          image: liscioapps/sphere-cubejs:1714137479.9d70374c
          env:
            - name: CUBEJS_DEV_MODE
              value: 'true'
            - name: CUBEJS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_DB_HOST
            - name: CUBEJS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_DB_PORT
            - name: CUBEJS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_DB_NAME
            - name: CUBEJS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_DB_USER
            - name: CUBEJS_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_DB_PASS
            - name: CUBEJS_DB_TYPE
              value: 'postgres'
            - name: CUBEJS_API_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CUBEJS_API_SECRET
            - name: CUBEJS_EXTERNAL_DEFAULT
              value: 'true'
            - name: CUBEJS_SCHEDULED_REFRESH_DEFAULT
              value: 'true'
          ports:
            - containerPort: 4000
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cubejs-svc
spec:
  selector:
    app: cubejs
  ports:
    - port: 4000
      targetPort: 4000
      name: management
    - port: 3000
      targetPort: 3000
      name: application
