---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-generator-dpl
  labels:
    force-reload: 'true'
spec:
  selector:
    matchLabels:
      app: job-generator
  template:
    metadata:
      labels:
        app: job-generator
    spec:
      containers:
        - name: job-generator
          image: liscioapps/sphere-backend:1714754233.e2fe998d
          workingDir: /usr/crowd/app/backend
          command: ['npm']
          args: ['run', 'start:job-generator']
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: SERVICE
              value: job-generator
