---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nango-dpl
spec:
  selector:
    matchLabels:
      app: nango
  template:
    metadata:
      labels:
        app: nango
    spec:
      containers:
        - name: nango
          image: nangohq/nango-server:0.9.0
          env:
            - name: NANGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_WRITE_HOST
            - name: NANGO_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PORT
            - name: NANGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_DATABASE
            - name: NANGO_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_USERNAME
            - name: NANGO_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PASSWORD
            - name: NANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_NANGO_SECRET_KEY
            - name: SERVER_PORT
              value: '3003'
            - name: NANGO_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_NANGO_URL_CALLBACK
            - name: NANGO_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VUE_APP_NANGO_URL
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: nango-svc
spec:
  type: ClusterIP
  selector:
    app: nango
  ports:
    - port: 3003
      targetPort: 3003
