---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dpl
spec:
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.7.0
          env:
            - name: discovery.type
              value: 'single-node'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
            - name: DISABLE_SECURITY_PLUGIN
              value: 'true'
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: 'false'
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
            limits:
              cpu: "2"
              memory: "6Gi"
            requests:
              cpu: "1"
              memory: "3Gi"

# Missing from test config
  # ulimits:
  #   memlock:
  #     soft: -1
  #     hard: -1
  #   nofile:
  #     soft: 65536
  #     hard: 65536
---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-svc
spec:
  type: ClusterIP
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9600
      targetPort: 9600
      name: transport
