---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzly-dpl
spec:
  selector:
    matchLabels:
      app: pizzly
  template:
    metadata:
      labels:
        app: pizzly
    spec:
      containers:
        - name: pizzly
          image: nangohq/pizzly-server:0.4.0
          env:
            - name: NANGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_WRITE_HOST
            - name: NANGO_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PORT
            - name: NANGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_DATABASE
            - name: NANGO_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_USERNAME
            - name: NANGO_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PASSWORD
            - name: PIZZLY_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_PIZZLY_SECRET_KEY
            - name: PIZZLY_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VUE_APP_PIZZLY_PUBLISHABLE_KEY
            - name: AUTH_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VUE_APP_PIZZLY_URL_CALLBACK

          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: pizzly-svc
spec:
  type: ClusterIP
  selector:
    app: pizzly
  ports:
    - port: 3003
      targetPort: 3003
