---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dpl
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: crowddotdev/redis:1669030011.68836df
          command: ['redis-server']
          args: ['/redis.conf', '--requirepass', 'crowdtest']
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
