---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-dpl
spec:
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: liscioapps/sphere-temporal:1714498867.7e0ff8f6
          ports:
            - containerPort: 7233
            - containerPort: 8233
          env:
            - name: POSTGRES_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_WRITE_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PORT
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_USERNAME
            - name: POSTGRES_PWD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_PASSWORD
            - name: SQL_TLS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_DB_SSL
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-svc
spec:
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233
      name: grpc
    - port: 8233
      targetPort: 8233
      name: webui
