---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-dpl
spec:
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
    spec:
      containers:
        - name: unleash
          image: unleashorg/unleash-server:latest
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_UNLEASH_DB_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_UNLEASH_DB_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_UNLEASH_DB_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_UNLEASH_DB_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CROWD_UNLEASH_DB_PASSWORD

          ports:
            - containerPort: 4242
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-svc
spec:
  type: ClusterIP
  selector:
    app: unleash
  ports:
    - port: 4242
      targetPort: 4242
