# image for building dependencies only
FROM python:3.8-bullseye as builder

RUN apt install -y --no-install-recommends gcc

WORKDIR /var/task

COPY . .

RUN  pip3 install --user psycopg2-binary && \
pip3 install --user -r requirements.txt && \
pip3 install --user -r requirements.dev.txt

ENTRYPOINT ["python", "-u", "python_worker.py"]
