FROM lambci/lambda:build-python3.8 as builder

USER root

RUN yum -y install gcc gcc-c++ postgresql-devel

WORKDIR /var/task

COPY . .

COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions /opt/extensions     

RUN  pip3 install psycopg2-binary && \
     pip3 install -r requirements.txt && \
     pip3 install -r requirements.dev.txt

FROM lambci/lambda:python3.8
COPY --from=builder /var/task /var/task
COPY --from=builder /var/lang/lib/python3.8/site-packages /var/lang/lib/python3.8/site-packages
COPY --from=builder /usr/lib64/libpq.so.5 /usr/lib64/libpq.so.5