name: Deployer
description: Custom Deployer Action

inputs:
  services:
    description: Services to deploy
    required: true
  tag:
    description: Tag for images
    required: false
    default: ${{ github.sha }}
  steps:
    description: Steps to run
    required: false
    default: build push deploy

runs:
  using: node16
  main: index.js
  post: index.js
