name: Deployer
description: Custom Deployer Action
author: urosh

inputs:
  services:
    description: Services to deploy
    required: true
  tag:
    description: Tag for images
    required: false
    default: ${{ github.sha }}

runs:
  using: node16
  main: index.js
  post: index.js
