FROM node:16-alpine as builder

WORKDIR /usr/crowd/frontend
RUN corepack enable

COPY ./pnpm-workspace.yaml ./pnpm-lock.yaml ./
COPY ./frontend ./frontend
RUN pnpm i --frozen-lockfile

FROM node:16-alpine as runner

WORKDIR /usr/crowd/frontend
RUN corepack enable

COPY --from=builder /usr/crowd/frontend/node_modules ./node_modules
COPY --from=builder /usr/crowd/frontend/frontend ./frontend
COPY ./frontend/.browserslistrc ./frontend/.eslintrc.js ./frontend/babel.config.js ./frontend/postcss.config.js ./frontend/tailwind.config.js ./frontend/vite.config.js ./frontend/tsconfig.json ./frontend/index.html ./frontend/
COPY ./frontend/public ./frontend/public
COPY ./frontend/src ./frontend/src