# syntax = docker/dockerfile:experimental
FROM node:19.6.0-bullseye-slim as builder
WORKDIR /usr/crowd/backend
COPY . .

RUN npm install && \
    npm run build && \
    cp ./package.json ./dist/package.json

FROM node:19.6.0-bullseye-slim
WORKDIR /usr/crowd/backend
COPY --from=builder /usr/crowd/backend/dist ./dist
RUN cd ./dist && npm install
CMD node dist/server.js