FROM node:16-alpine as builder

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 build-base && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

WORKDIR /usr/crowd/backend
COPY package-lock.json package.json ./

RUN npm install

FROM node:16-alpine

COPY --from=builder /usr/crowd/backend/node_modules ./node_modules
COPY . .