FROM python:3.8-bullseye

RUN apt install -y --no-install-recommends gcc

WORKDIR /var/task

COPY . .

RUN python -m venv --copies ./venv && . ./venv/bin/activate && \
  python --version && which python && \
  pip --version && which pip && \
  ls ./venv/bin

RUN  pip install -r requirements.txt
USER root
RUN mkdir /.cache && chmod -R 777 /.cache
