FROM python:3.8-bullseye

RUN apt install -y --no-install-recommends gcc

WORKDIR /var/task

COPY ./requirements.txt ./
COPY ./crowd-eagle-eye/setup.py ./crowd-eagle-eye/

RUN python -m venv --copies ./venv && . ./venv/bin/activate && ./venv/bin/pip install -r requirements.txt

COPY . .

USER root
RUN mkdir /.cache && chmod -R 777 /.cache
