version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: api
  SHELL: /bin/sh

services:
  api:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:api'
    working_dir: /usr/crowd/app/backend
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    ports:
      - '8080:8080'
    restart: always
    networks:
      - crowd-bridge

  api-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
      args:
        INSTALL_DEV_DEPENDENCIES: 'true'
    command: 'npm run start:api:dev'
    working_dir: /usr/crowd/app/backend
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    hostname: api
    ports:
      - '8080:8080'
    networks:
      - crowd-bridge
    volumes:
      - ../../backend:/usr/crowd/app/backend
      - /usr/crowd/app/backend/node_modules

networks:
  crowd-bridge:
    external: true
