version: '3.1'

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:api'
    environment:
      - DOCKER_BUILDKIT=1
      - NODE_ENV=docker
      - SERVICE_NAME=api
      - TENANT_MODE=multi
    networks:
      - crowd-bridge

  api-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:api'
    environment:
      - DOCKER_BUILDKIT=1
      - NODE_ENV=docker
      - SERVICE_NAME=api
      - TENANT_MODE=multi
    hostname: api
    networks:
      - crowd-bridge
    volumes:
      - ../../backend:/usr/crowd/backend

networks:
  crowd-bridge:
    external: true
