version: '3.1'

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    env_file:
      - ../../backend/.env
    command: 'npm start'
    environment:
      - DOCKER_BUILDKIT=1
    networks:
      - crowd-bridge

  api-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    env_file:
      - ../../backend/.env
    command: 'npm start'
    environment:
      - DOCKER_BUILDKIT=1
    networks:
      - crowd-bridge
    hostname: backend
    volumes:
      - ../../backend:/usr/crowd/backend

networks:
  crowd-bridge:
    external: true
