version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: conversations

services:
  community-help-center:
    build:
      context: ../premium/community-help-center
      dockerfile: Dockerfile.dev
    command: 'npm run dev'
    ports:
      - '3000:3000'
      - '24678:24678' #vite server port
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    restart: always
    networks:
      - crowd-bridge

  community-help-center-dev:
    build:
      context: ../premium/community-help-center
      dockerfile: Dockerfile.dev
    command: 'npm run dev'
    ports:
      - '3000:3000'
      - '24678:24678' #vite server port
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    hostname: community-help-center
    networks:
      - crowd-bridge
    volumes:
      - ../../premium/community-help-center/assets:/usr/crowd/community-help-center/assets
      - ../../premium/community-help-center/components:/usr/crowd/community-help-center/components
      - ../../premium/community-help-center/composables:/usr/crowd/community-help-center/composables
      - ../../premium/community-help-center/helpers:/usr/crowd/community-help-center/helpers
      - ../../premium/community-help-center/pages:/usr/crowd/community-help-center/pages
      - ../../premium/community-help-center/public:/usr/crowd/community-help-center/public
      - ../../premium/community-help-center/sample-data:/usr/crowd/community-help-center/sample-data
      - ../../premium/community-help-center/server:/usr/crowd/community-help-center/server
      - ../../premium/community-help-center/app.vue:/usr/crowd/community-help-center/app.vue

networks:
  crowd-bridge:
    external: true
