version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: conversations

services:
  conversations:
    build:
      context: ../premium/conversations
      dockerfile: Dockerfile.dev
    command: 'npm run dev'
    ports:
      - '3000:3000'
      - '24678:24678' #vite server port
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    networks:
      - crowd-bridge

  conversations-dev:
    build:
      context: ../premium/conversations
      dockerfile: Dockerfile.dev
    command: 'npm run dev'
    ports:
      - '3000:3000'
      - '24678:24678' #vite server port
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    hostname: conversations
    networks:
      - crowd-bridge
    volumes:
      - ../../premium/conversations/assets:/usr/crowd/conversations/assets
      - ../../premium/conversations/components:/usr/crowd/conversations/components
      - ../../premium/conversations/composables:/usr/crowd/conversations/composables
      - ../../premium/conversations/helpers:/usr/crowd/conversations/helpers
      - ../../premium/conversations/pages:/usr/crowd/conversations/pages
      - ../../premium/conversations/public:/usr/crowd/conversations/public
      - ../../premium/conversations/sample-data:/usr/crowd/conversations/sample-data
      - ../../premium/conversations/server:/usr/crowd/conversations/server
      - ../../premium/conversations/app.vue:/usr/crowd/conversations/app.vue

networks:
  crowd-bridge:
    external: true
