version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: discord-ws
  SHELL: /bin/sh

services:
  discord-ws:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:discord-ws'
    working_dir: /usr/crowd/app/backend
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    restart: always
    networks:
      - crowd-bridge

  discord-ws-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
      args:
        INSTALL_DEV_DEPENDENCIES: 'true'
    command: 'npm run start:discord-ws:dev'
    working_dir: /usr/crowd/app/backend
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    networks:
      - crowd-bridge
    volumes:
      - ../../backend/src:/usr/crowd/app/backend/src
      - /usr/crowd/app/backend/node_modules

networks:
  crowd-bridge:
    external: true
