version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: job-generator
  SHELL: /bin/sh

services:
  job-generator:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:job-generator'
    working_dir: /usr/crowd/app/backend
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    restart: always
    networks:
      - crowd-bridge

  job-generator-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:job-generator:dev'
    working_dir: /usr/crowd/app/backend
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    hostname: job-generator
    networks:
      - crowd-bridge
    volumes:
      - ../../backend:/usr/crowd/app/backend
      - /usr/crowd/app/backend/node_modules

networks:
  crowd-bridge:
    external: true
