version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: job-generator
  TENANT_MODE: multi
  KUBE_MODE: 1

services:
  job-generator:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:job-generator'
    environment:
      <<: *env-args
    networks:
      - crowd-bridge

  job-generator-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:job-generator'
    user: '${USER_ID}:${GROUP_ID}'
    environment:
      <<: *env-args
    hostname: job-generator
    networks:
      - crowd-bridge
    volumes:
      - ../../backend:/usr/crowd/backend
      - /usr/crowd/backend/node_modules

networks:
  crowd-bridge:
    external: true
