version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: nango-webhook-api
  SHELL: /bin/sh

services:
  nango-webhook-api:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.nango_webhook_api
    command: 'pnpm run start'
    working_dir: /usr/crowd/app/services/apps/nango_webhook_api
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    ports:
      - '8084:8084'
    restart: always
    networks:
      - crowd-bridge

  nango-webhook-api-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.nango_webhook_api
    command: 'pnpm run dev'
    working_dir: /usr/crowd/app/services/apps/nango_webhook_api
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
    hostname: nango-webhook-api
    ports:
      - '8084:8084'
    networks:
      - crowd-bridge
    volumes:
      - ../../services/libs/audit-logs/src:/usr/crowd/app/services/libs/audit-logs/src
      - ../../services/libs/common/src:/usr/crowd/app/services/libs/common/src
      - ../../services/libs/common_services/src:/usr/crowd/app/services/libs/common_services/src
      - ../../services/libs/data-access-layer/src:/usr/crowd/app/services/libs/data-access-layer/src
      - ../../services/libs/database/src:/usr/crowd/app/services/libs/database/src
      - ../../services/libs/integrations/src:/usr/crowd/app/services/libs/integrations/src
      - ../../services/libs/logging/src:/usr/crowd/app/services/libs/logging/src
      - ../../services/libs/nango/src:/usr/crowd/app/services/libs/nango/src
      - ../../services/libs/opensearch/src:/usr/crowd/app/services/libs/opensearch/src
      - ../../services/libs/queue/src:/usr/crowd/app/services/libs/queue/src
      - ../../services/libs/redis/src:/usr/crowd/app/services/libs/redis/src
      - ../../services/libs/snowflake/src:/usr/crowd/app/services/libs/snowflake/src
      - ../../services/libs/telemetry/src:/usr/crowd/app/services/libs/telemetry/src
      - ../../services/libs/temporal/src:/usr/crowd/app/services/libs/temporal/src
      - ../../services/libs/types/src:/usr/crowd/app/services/libs/types/src
      - ../../services/apps/nango_webhook_api/src:/usr/crowd/app/services/apps/nango_webhook_api/src

networks:
  crowd-bridge:
    external: true
