version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: nodejs-worker
  TENANT_MODE: multi
  KUBE_MODE: 1

services:
  nodejs-worker:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:nodejs-worker'
    env_file:
      - ../../backend/.env.local
      - ../../backend/.env.docker
    environment:
      <<: *env-args
    networks:
      - crowd-bridge

  nodejs-worker-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile-api-dev
    command: 'npm run start:nodejs-worker'
    user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.local
      - ../../backend/.env.docker
    environment:
      <<: *env-args
    hostname: nodejs-worker
    networks:
      - crowd-bridge
    volumes:
      - ../../backend:/usr/crowd/backend
      - /usr/crowd/backend/node_modules

networks:
  crowd-bridge:
    external: true
