export enum TanstackKey {
  ADMIN_COLLECTIONS = 'admin-collections',
  ADMIN_INSIGHTS_PROJECTS = 'admin-insights-projects',
  ADMIN_PROJECT_GROUPS = 'admin-project-groups',
  ADMIN_SUB_PROJECTS = 'admin-sub-projects',
  MEMBER_MERGE_SUGGESTIONS_COUNT = 'member-merge-suggestions-count',
  MEMBERS_LIST = 'members-list',
  ORGANIZATION_MERGE_SUGGESTIONS_COUNT = 'organization-merge-suggestions-count',
  ORGANIZATIONS_LIST = 'organizations-list',
  GLOBAL_INTEGRATION_STATUS_COUNT = 'global-integration-status-count',
  GLOBAL_INTEGRATIONS = 'global-integrations',
  PROJECT_BY_ID = 'project-by-id',
  DASHBOARD_METRICS = 'dashboard-metrics',
  INTEGRATION_PROGRESS_LIST = 'integration-progress-list',
}
