version: '3.1'

services:
  db-test:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crowd-web
    ports:
      - 5433:5432
    networks:
      - crowd-bridge-test
  search-engine-test:
    image: getmeili/meilisearch:v0.27.2
    ports:
      - 7701:7700
    networks:
      - crowd-bridge-test

  redis-test:
    image: redis
    ports:
      - 6380:6379
    networks:
      - crowd-bridge-test

networks:
  crowd-bridge-test:
    external: true
