# syntax = docker/dockerfile:experimental
## After `aws configure` in the host machine(needed to connect s3),
## build using `DOCKER_BUILDKIT=1 docker build -t anilbostanci/crowd-db-staging:0.0.14 --secret id=aws,src=$HOME/.aws/credentials .`
FROM postgres:13
RUN apt update && apt install -y curl zip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN --mount=type=secret,id=aws,target=/root/.aws/credentials aws s3 cp s3://crowdweb/database/2022-04-06-staging-dump /db-data-init/staging_dump
COPY initialize-data.sh /docker-entrypoint-initdb.d/initialize-data.sh
RUN chmod o+x /docker-entrypoint-initdb.d/initialize-data.sh
