FROM flyway/flyway:7.8.1-alpine

USER root

# Install envsubst from gettext used for templating.
RUN apk update \
  && apk add --no-cache gettext

USER flyway
COPY ./flyway_migrate.sh /
# Copy migrations.
COPY ./migrations /app/




# Override default `flyway` entrypoint.
ENTRYPOINT [ "/flyway_migrate.sh" ] 

