ALTER TABLE public."organizations" DROP COLUMN "affiliatedProfiles";
ALTER TABLE public."organizations" DROP COLUMN "allSubsidiaries";
ALTER TABLE public."organizations" DROP COLUMN "alternativeDomains";
ALTER TABLE public."organizations" DROP COLUMN "alternativeNames";
ALTER TABLE public."organizations" DROP COLUMN "averageEmployeeTenure";
ALTER TABLE public."organizations" DROP COLUMN "averageTenureByLevel";
ALTER TABLE public."organizations" DROP COLUMN "averageTenureByRole";
ALTER TABLE public."organizations" DROP COLUMN "directSubsidiaries";
ALTER TABLE public."organizations" DROP COLUMN "employeeChurnRate";
ALTER TABLE public."organizations" DROP COLUMN "employeeCountByMonth";
ALTER TABLE public."organizations" DROP COLUMN "employeeGrowthRate";
ALTER TABLE public."organizations" DROP COLUMN "employeeCountByMonthByLevel";
ALTER TABLE public."organizations" DROP COLUMN "employeeCountByMonthByRole";
ALTER TABLE public."organizations" DROP COLUMN "gicsSector";
ALTER TABLE public."organizations" DROP COLUMN "grossAdditionsByMonth";
ALTER TABLE public."organizations" DROP COLUMN "grossDeparturesByMonth";
ALTER TABLE public."organizations" DROP COLUMN "recentExecutiveDepartures";
ALTER TABLE public."organizations" DROP COLUMN "recentExecutiveHires";
ALTER TABLE public."organizations" DROP COLUMN "ultimateParent";
ALTER TABLE public."organizations" DROP COLUMN "immediateParent";
ALTER TABLE public."organizations" ADD COLUMN "parentUrl" TEXT NULL;
ALTER TABLE public."organizationCaches" ADD COLUMN "parentUrl" TEXT NULL;