DROP TABLE IF EXISTS widgets CASCADE;
DROP TABLE IF EXISTS reports CASCADE;

DROP MATERIALIZED VIEW IF EXISTS mv_activities_cube CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_organizations_cube CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_segments_cube CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_members_cube CASCADE;
