drop table tasks;
drop table taskAssignees;
drop table memberTasks;
drop table activityTasks;
drop table notes;
drop table memberNotes;
drop table microservices;
drop table automations;
drop table automationExecutions;
drop table recurringEmailsHistory;

drop table member_identities_backup;
drop table member_organizations_identities_backup;
drop table members_backup;
drop table membersSyncRemote;

drop table old_organizationCacheLinks;
drop table old_organizationCacheIdentities;
drop table old_organizationCache;
drop table organizationToMergeOld;
drop table organization_identities_backup;
drop table organizationsSyncRemote;

alter table organizations drop column old_emails;
alter table organizations drop column old_phonenumbers;
alter table organizations drop column old_twitter;
alter table organizations drop column old_linkedin;
alter table organizations drop column old_crunchbase;
alter table organizations drop column old_employeecountbycountry;
alter table organizations drop column old_geolocation;
alter table organizations drop column old_ticker;
alter table organizations drop column old_profiles;
alter table organizations drop column old_address;
alter table organizations drop column old_attributes;
alter table organizations drop column old_affiliatedprofiles;
alter table organizations drop column old_allsubsidiaries;
alter table organizations drop column old_alternativedomains;
alter table organizations drop column old_alternativenames;
alter table organizations drop column old_averageemployeetenure;
alter table organizations drop column old_averagetenurebylevel;
alter table organizations drop column old_averagetenurebyrole;
alter table organizations drop column old_directsubsidiaries;
alter table organizations drop column old_employeecountbymonth;
alter table organizations drop column old_employeecountbymonthbylevel;
alter table organizations drop column old_employeecountbymonthbyrole;
alter table organizations drop column old_gicssector;
alter table organizations drop column old_grossadditionsbymonth;
alter table organizations drop column old_grossdeparturesbymonth;
alter table organizations drop column old_ultimateparent;
alter table organizations drop column old_immediateparent;
alter table organizations drop column old_weakidentities;
alter table organizations drop column old_manuallychangedfields;
alter table organizations drop column old_naics;
alter table organizations drop column old_names;