export const mockPullRequests = {
  data: {
    repository: {
      pullRequests: {
        pageInfo: {
          hasPreviousPage: true,
          startCursor: 'Y3Vyc29yOnYyOpHOPC8wZg==',
        },
        nodes: [
          {
            author: {
              login: 'tuves',
              name: null,
              id: 'MDQ6VXNlcjQ5OTE1NzQ5',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/tuves',
              websiteUrl: null,
              email: '',
              bio: 'Senior Program Manager, @github Community',
              company: null,
              location: null,
            },
            bodyText: 'fixed extra text',
            state: 'MERGED',
            title: 'update readme',
            id: 'PR_kwDOEfmk4M48LzBm',
            url: 'https://github.com/community/community/pull/27306',
            createdAt: '2022-07-27T14:14:55Z',
            number: 27306,
          },
          {
            author: {
              login: 'tuves',
              name: null,
              id: 'MDQ6VXNlcjQ5OTE1NzQ5',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/tuves',
              websiteUrl: null,
              email: '',
              bio: 'Senior Program Manager, @github Community',
              company: null,
              location: null,
            },
            bodyText: 'removed duplicative paragraph and extra line in table',
            state: 'MERGED',
            title: 'update readme',
            id: 'PR_kwDOEfmk4M48L1QX',
            url: 'https://github.com/community/community/pull/27308',
            createdAt: '2022-07-27T14:22:37Z',
            number: 27308,
          },
          {
            author: {
              login: 'natalierjackson',
              name: 'Natalie Rodriguez-Jackson',
              id: 'U_kgDOBeFlZw',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/natalierjackson',
              websiteUrl: null,
              email: '',
              bio: 'product operations @github ',
              company: null,
              location: null,
            },
            bodyText: '',
            state: 'MERGED',
            title: 'Update read for api and webhooks category request',
            id: 'PR_kwDOEfmk4M485x02',
            url: 'https://github.com/community/community/pull/28911',
            createdAt: '2022-08-09T17:18:52Z',
            number: 28911,
          },
          {
            author: {
              login: 'natalierjackson',
              name: 'Natalie Rodriguez-Jackson',
              id: 'U_kgDOBeFlZw',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/natalierjackson',
              websiteUrl: null,
              email: '',
              bio: 'product operations @github ',
              company: null,
              location: null,
            },
            bodyText: '',
            state: 'MERGED',
            title: 'Update to include new category pages',
            id: 'PR_kwDOEfmk4M49U5AU',
            url: 'https://github.com/community/community/pull/29812',
            createdAt: '2022-08-17T14:02:04Z',
            number: 29812,
          },
          {
            author: {
              login: 'Krisdtisak',
              name: 'Kriadtisak',
              id: 'U_kgDOBqbDtQ',
              isHireable: false,
              twitterUsername: 'Krisdtisak-tw',
              url: 'https://github.com/Krisdtisak',
              websiteUrl: 'K',
              email: 'some@email.com',
              bio: 'Kkkk',
              company: 'K',
              location: 'K',
            },
            bodyText: 'some-body',
            state: 'OPEN',
            title: ' krisdtisak',
            id: 'PR_kwDOEfmk4M49fwEH',
            url: 'https://github.com/community/community/pull/30181',
            createdAt: '2022-08-20T09:08:53Z',
            number: 30181,
          },
        ],
      },
    },
  },
}

export const mockIssues = {
  data: {
    repository: {
      issues: {
        pageInfo: {
          hasPreviousPage: true,
          startCursor: 'Y3Vyc29yOnYyOpHOT8lOKQ==',
        },
        nodes: [
          {
            author: {
              login: 'zpawn',
              name: 'ilia makarov',
              id: 'MDQ6VXNlcjExMDQzMTIw',
              isHireable: true,
              twitterUsername: 'someTwitterUsername',
              url: 'https://github.com/zpawn',
              websiteUrl: 'https://a-website.com',
              email: 'ilia.makarov@me.com',
              bio: 'A Nice BIO',
              company: 'Crowd.dev',
              location: 'Berlin',
            },
            bodyText:
              'Description\nIn some cases useState updater function sees an irrelevant value\nReact version: 16.8.0, 17.0.2, 18.0.0\nSteps To Reproduce\n\nPress setCount button\nPress setCount button again\nSee the console input\n\nLink to code example: codesandox example',
            state: 'CLOSED',
            id: 'I_kwDOAJy2Ks5PyU4p',
            title: 'Bug: inconsistent recursive setState() behavior',
            url: 'https://github.com/facebook/react/issues/25098',
            createdAt: '2022-08-15T06:25:39Z',
            number: 25098,
          },
          {
            author: {
              login: 'mp3846',
              name: 'Mostafa Pourmorad',
              id: 'MDQ6VXNlcjU0MzMwNDg1',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/mp3846',
              websiteUrl: null,
              email: 'mpourmorad@gmail.com',
              bio: '',
              company: null,
              location: null,
            },
            bodyText:
              'CodeSandBox\nwrite some text and try to undo using ctrl+z, it does not work\ngo to middle of sentence and start typing, it will jump to end after typing one character!',
            state: 'CLOSED',
            id: 'I_kwDOAJy2Ks5P1BKb',
            title:
              'using startTransition for textarea => ctrl+z not working and typing jumps to end',
            url: 'https://github.com/facebook/react/issues/25099',
            createdAt: '2022-08-15T18:07:48Z',
            number: 25099,
          },
          {
            author: {
              login: 'whatwg6',
              name: null,
              id: 'MDQ6VXNlcjE4NDk5MTUz',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/whatwg6',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: 'Beijing',
            },
            bodyText:
              'React version: 18.2.0\nSteps To Reproduce\nimport { createRoot } from "react-dom/client";\n\nconst root = document.getElementById("root");\nconst fragment = document.createDocumentFragment();\nroot.appendChild(fragment);\n\nconst browsers = ["Firefox", "Chrome", "Opera", "Safari", "Internet Explorer"];\n\nconst App = () => browsers.map((browser) => <div key={browser}>{browser}</div>);\n\ncreateRoot(fragment).render(<App />);\n\nLink to code example:\nhttps://codesandbox.io/s/react18-createroot-documentfragment-qhoxog\nThe current behavior\ndoes not render UI\nThe expected behavior\nrender UI',
            state: 'CLOSED',
            id: 'I_kwDOAJy2Ks5P3oaq',
            title: 'Bug: createRoot with DocumentFragment does not render to dom',
            url: 'https://github.com/facebook/react/issues/25101',
            createdAt: '2022-08-16T08:16:41Z',
            number: 25101,
          },
          {
            author: {
              login: 'ikhtearalamshawonmollah54321',
              name: 'Md. Ikhtear Alam Shawon Mollah',
              id: 'U_kgDOBlM-lQ',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/ikhtearalamshawonmollah54321',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
            bodyText: 'We did that.\nOriginally posted by @gaearon in #11689 (comment)',
            state: 'CLOSED',
            id: 'I_kwDOAJy2Ks5QEyMJ',
            title: 'We did that.',
            url: 'https://github.com/facebook/react/issues/25116',
            createdAt: '2022-08-18T18:02:57Z',
            number: 25116,
          },
          {
            author: {
              login: 'DXJ999empireZ',
              name: null,
              id: 'U_kgDOBmO-bg',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/DXJ999empireZ',
              websiteUrl: null,
              email: '',
              bio: null,
              company: null,
              location: null,
            },
            bodyText: 'Link to code example:\n\nThe current behavior\nThe expected behavior',
            state: 'CLOSED',
            id: 'I_kwDOAJy2Ks5QH3Cl',
            title: 'Bug: ',
            url: 'https://github.com/facebook/react/issues/25120',
            createdAt: '2022-08-19T10:12:08Z',
            number: 25120,
          },
        ],
      },
    },
  },
}

export const mockForks = {
  data: {
    repository: {
      forks: {
        pageInfo: {
          hasPreviousPage: true,
          startCursor: 'Y3Vyc29yOnYyOpHOH2z9pA==',
        },
        nodes: [
          {
            owner: {
              login: 'shimeng28',
              name: 'eric_shi',
              id: 'MDQ6VXNlcjIwNjE5NTky',
              isHireable: true,
              twitterUsername: 'a-twitter-username',
              url: 'https://github.com/shimeng28',
              websiteUrl: 'http://www.shimeng.info',
              email: 'shimeng.eric@gmail.com',
              bio: 'wechat: shi0280',
              company: 'bytedance',
              location: 'shenzhen',
            },
            name: 'react',
            url: 'https://github.com/shimeng28/react',
            id: 'R_kgDOH2z9pA',
            createdAt: '2022-08-21T14:50:42Z',
          },
          {
            owner: {
              login: 'Bhavesh38',
              name: 'Bhavesh kumar',
              id: 'MDQ6VXNlcjkwMTMyNDg5',
              isHireable: false,
              twitterUsername: 'itsbhaveshkumar',
              url: 'https://github.com/Bhavesh38',
              websiteUrl: 'https://bhavesh38.github.io/Bhavesh-s-Portfolio/',
              email: '',
              bio: "I'm Bhavesh Kumar currently studying in 3rd year of institute of Engineering and Management ,Kolkata in Compute science and Engineering.I have love for problem.",
              company: 'Institute of Engineering and ManageMent, Kolkata',
              location: 'Kolkata',
            },
            name: 'react',
            url: 'https://github.com/Bhavesh38/react',
            id: 'R_kgDOH20uSA',
            createdAt: '2022-08-21T15:36:49Z',
          },
          {
            owner: {
              login: '1harshal',
              name: 'Harshal Anand Badgujar',
              id: 'MDQ6VXNlcjUzNjU0OTc3',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/1harshal',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
            name: 'react',
            url: 'https://github.com/1harshal/react',
            id: 'R_kgDOH21wjQ',
            createdAt: '2022-08-21T16:41:33Z',
          },
          {
            owner: {
              login: 'YutoSekiguchi',
              name: null,
              id: 'MDQ6VXNlcjY0MDI3OTk2',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/YutoSekiguchi',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
            name: 'react',
            url: 'https://github.com/YutoSekiguchi/react',
            id: 'R_kgDOH22h5Q',
            createdAt: '2022-08-21T17:30:11Z',
          },
          {
            owner: {
              login: '472654243',
              name: 'dingyi',
              id: 'MDQ6VXNlcjIwMTc3MzQ3',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/472654243',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
            name: 'react',
            url: 'https://github.com/472654243/react',
            id: 'R_kgDOH22rUg',
            createdAt: '2022-08-21T17:39:40Z',
          },
        ],
      },
    },
  },
}

export const mockStars = {
  data: {
    repository: {
      stargazers: {
        pageInfo: {
          hasPreviousPage: true,
          startCursor: 'Y3Vyc29yOnYyOpIAzhUOGGM=',
        },
        totalCount: 193541,
        edges: [
          {
            starredAt: '2022-08-21T18:04:26Z',
            node: {
              login: 'tessarobyn',
              name: 'Tessa',
              id: 'U_kgDOBni1pw',
              isHireable: true,
              twitterUsername: 'some-twitter-username',
              url: 'https://github.com/tessarobyn',
              websiteUrl: 'https://some.website',
              email: 'some@email.com',
              bio: 'Programming enthusiast :)',
              company: 'Crowd.dev',
              location: 'Berlin',
            },
          },
          {
            starredAt: '2022-08-21T18:19:15Z',
            node: {
              login: 'prajulaaditya007',
              name: null,
              id: 'MDQ6VXNlcjgwMTkxMTk4',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/prajulaaditya007',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
          },
          {
            starredAt: '2022-08-21T19:05:53Z',
            node: {
              login: 'HumbertoDiego',
              name: 'Humberto Alves',
              id: 'MDQ6VXNlcjI2MDcyMTM2',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/HumbertoDiego',
              websiteUrl: null,
              email: 'humberto-xingu@live.com',
              bio: '',
              company: null,
              location: null,
            },
          },
          {
            starredAt: '2022-08-21T19:07:15Z',
            node: {
              login: 'ArtemKlyuev',
              name: null,
              id: 'MDQ6VXNlcjM2NjUwMjAx',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/ArtemKlyuev',
              websiteUrl: null,
              email: '',
              bio: null,
              company: null,
              location: null,
            },
          },
          {
            starredAt: '2022-08-21T19:34:17Z',
            node: {
              login: 'bethgrey',
              name: 'bethgrey',
              id: 'U_kgDOBqO3Wg',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/bethgrey',
              websiteUrl: null,
              email: '',
              bio: '',
              company: null,
              location: null,
            },
          },
        ],
      },
    },
  },
}

export const mockPullRequestComments = {
  data: {
    repository: {
      pullRequest: {
        comments: {
          pageInfo: {
            hasPreviousPage: true,
            startCursor: 'Y3Vyc29yOnYyOpHOQtqJ6Q==',
          },
          nodes: [
            {
              author: {
                login: 'sachinraja',
                name: 'Sachin Raja',
                id: 'MDQ6VXNlcjU4ODM2NzYw',
                isHireable: false,
                twitterUsername: 's4chinraja',
                url: 'https://github.com/sachinraja',
                websiteUrl: null,
                email: 'sachinraja2349@gmail.com',
                bio: '@trpc core',
                company: null,
                location: 'California',
              },
              bodyText:
                'This would help support React Native and be esm compliant. In TanStack/query#3582 RN support was broken because we imported from use-sync-external-store/shim/index.js to support esm which does not support directory imports and must use extensions. With this PR we can import from use-sync-external-store/shim which would work correctly for esm and RN.',
              url: 'https://github.com/facebook/react/pull/24440#issuecomment-1121618409',
              id: 'IC_kwDOAJy2Ks5C2onp',
              createdAt: '2022-05-09T21:50:44Z',
              pullRequest: {
                url: 'https://github.com/facebook/react/pull/24440',
                id: 'PR_kwDOAJy2Ks42zbEl',
                title: 'Add "exports" field to use-sync-external-store\'s package.json',
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'TkDodo',
                name: 'Dominik Dorfmeister',
                id: 'MDQ6VXNlcjEwMjE0MzA=',
                isHireable: false,
                twitterUsername: 'TkDodo',
                url: 'https://github.com/TkDodo',
                websiteUrl: 'tkdodo.eu',
                email: '',
                bio: '',
                company: null,
                location: 'Vienna, Austria',
              },
              bodyText:
                '@gaearon @acdlite I think this PR would fix our issues we have over in react-query with the uSES shim for react native. apollo-client is having the same issue, and they have opted to copy over the uSES code to fix it on their side. I would rather wait for an official fix on your end, which I think this PR provides :)',
              url: 'https://github.com/facebook/react/pull/24440#issuecomment-1122076094',
              id: 'IC_kwDOAJy2Ks5C4YW-',
              createdAt: '2022-05-10T08:16:52Z',
              pullRequest: {
                url: 'https://github.com/facebook/react/pull/24440',
                id: 'PR_kwDOAJy2Ks42zbEl',
                title: 'Add "exports" field to use-sync-external-store\'s package.json',
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'latin-1',
                name: 'Hikari Hayashi',
                id: 'MDQ6VXNlcjQ0OTQ2Njk5',
                isHireable: false,
                twitterUsername: 'rev__hikari',
                url: 'https://github.com/latin-1',
                websiteUrl: 'https://hikari.im/',
                email: 'rev.hikari@gmail.com',
                bio: '「···」',
                company: null,
                location: null,
              },
              bodyText:
                "I had to say this would be a breaking change, though. That's why I held this PR. I'm trying to find out a better approach but with no luck.",
              url: 'https://github.com/facebook/react/pull/24440#issuecomment-1122151535',
              id: 'IC_kwDOAJy2Ks5C4qxv',
              createdAt: '2022-05-10T09:28:33Z',
              pullRequest: {
                url: 'https://github.com/facebook/react/pull/24440',
                id: 'PR_kwDOAJy2Ks42zbEl',
                title: 'Add "exports" field to use-sync-external-store\'s package.json',
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'gaearon',
                name: 'dan',
                id: 'MDQ6VXNlcjgxMDQzOA==',
                isHireable: false,
                twitterUsername: 'dan_abramov',
                url: 'https://github.com/gaearon',
                websiteUrl: null,
                email: 'dan.abramov@gmail.com',
                bio: '',
                company: '@facebook ',
                location: null,
              },
              bodyText: '@latin-1 What makes this a breaking change?',
              url: 'https://github.com/facebook/react/pull/24440#issuecomment-1139596251',
              id: 'IC_kwDOAJy2Ks5D7Nvb',
              createdAt: '2022-05-27T13:00:04Z',
              pullRequest: {
                url: 'https://github.com/facebook/react/pull/24440',
                id: 'PR_kwDOAJy2Ks42zbEl',
                title: 'Add "exports" field to use-sync-external-store\'s package.json',
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'sachinraja',
                name: 'Sachin Raja',
                id: 'MDQ6VXNlcjU4ODM2NzYw',
                isHireable: false,
                twitterUsername: 's4chinraja',
                url: 'https://github.com/sachinraja',
                websiteUrl: null,
                email: 'sachinraja2349@gmail.com',
                bio: '@trpc core',
                company: null,
                location: 'California',
              },
              bodyText:
                '@gaearon You can no longer import with extensions and some paths have changed (for ESM resolution):\nuse-sync-external-store/index.js -> use-sync-external-store\nuse-sync-external-store/shim/index.js -> use-sync-external-store/shim\nuse-sync-external-store/with-selector.js -> use-sync-external-store/with-selector\n\nWe may be able to support it by just exporting everything under the same path as before (maybe using glob exports).',
              url: 'https://github.com/facebook/react/pull/24440#issuecomment-1139607249',
              id: 'IC_kwDOAJy2Ks5D7QbR',
              createdAt: '2022-05-27T13:13:52Z',
              pullRequest: {
                url: 'https://github.com/facebook/react/pull/24440',
                id: 'PR_kwDOAJy2Ks42zbEl',
                title: 'Add "exports" field to use-sync-external-store\'s package.json',
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
          ],
        },
      },
    },
  },
}

export const mockIssueComments = {
  data: {
    repository: {
      issue: {
        comments: {
          pageInfo: {
            hasPreviousPage: false,
            startCursor: 'Y3Vyc29yOnYyOpHOARy7IQ==',
          },
          nodes: [
            {
              author: {
                login: 'zpao',
                name: 'Paul O’Shannessy',
                id: 'MDQ6VXNlcjg0NDU=',
                isHireable: false,
                twitterUsername: 'zpao',
                url: 'https://github.com/zpao',
                websiteUrl: 'https://zpao.com',
                email: 'paul@oshannessy.com',
                bio: 'I do open source things at @facebook.',
                company: '@facebook ',
                location: 'Seattle, WA',
              },
              bodyText:
                "Bah, I changed build filenames last minute and didn't properly test the module after :( Thanks for finding this! I guess we should write some tests for the node module too, not just our phantomjs tests.\n(Very) Short term, you should be able to change ./build/React to ./build/react and that will fix the problem.\n@benjamn - I guess it's time to figure out what we want to do with npm versions vs library versions. Should we just bump them both for the time being?",
              url: 'https://github.com/facebook/react/issues/10#issuecomment-18660129',
              id: 'MDEyOklzc3VlQ29tbWVudDE4NjYwMTI5',
              createdAt: '2013-05-30T03:53:16Z',
              issue: {
                url: 'https://github.com/facebook/react/issues/10',
                id: 'MDU6SXNzdWUxNDkyMzk2OA==',
                title: "Can't require() react-tools module",
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'zpao',
                name: 'Paul O’Shannessy',
                id: 'MDQ6VXNlcjg0NDU=',
                isHireable: false,
                twitterUsername: 'zpao',
                url: 'https://github.com/zpao',
                websiteUrl: 'https://zpao.com',
                email: 'paul@oshannessy.com',
                bio: 'I do open source things at @facebook.',
                company: '@facebook ',
                location: 'Seattle, WA',
              },
              bodyText:
                "Nope, that alone won't do it, we're not even packaging. I totally screwed up the node module :( Fix soon!",
              url: 'https://github.com/facebook/react/issues/10#issuecomment-18660323',
              id: 'MDEyOklzc3VlQ29tbWVudDE4NjYwMzIz',
              createdAt: '2013-05-30T04:01:21Z',
              issue: {
                url: 'https://github.com/facebook/react/issues/10',
                id: 'MDU6SXNzdWUxNDkyMzk2OA==',
                title: "Can't require() react-tools module",
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
            {
              author: {
                login: 'jriecken',
                name: 'Jim Riecken',
                id: 'MDQ6VXNlcjQwODgyNQ==',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/jriecken',
                websiteUrl: 'https://www.jimr.ca',
                email: '',
                bio: '',
                company: null,
                location: 'Vancouver, BC',
              },
              bodyText: "Yeah, doesn't look like there's even a build directory there. :)",
              url: 'https://github.com/facebook/react/issues/10#issuecomment-18660385',
              id: 'MDEyOklzc3VlQ29tbWVudDE4NjYwMzg1',
              createdAt: '2013-05-30T04:03:35Z',
              issue: {
                url: 'https://github.com/facebook/react/issues/10',
                id: 'MDU6SXNzdWUxNDkyMzk2OA==',
                title: "Can't require() react-tools module",
              },
              repository: {
                url: 'https://github.com/facebook/react',
              },
            },
          ],
        },
      },
    },
  },
}

export const mockDiscussions = {
  data: {
    repository: {
      discussions: {
        pageInfo: {
          hasPreviousPage: true,
          startCursor: 'Y3Vyc29yOnYyOpK5MjAxNy0xMS0wMlQxODowMzoxMCswMTowMM4AQNBD',
        },
        nodes: [
          {
            author: {
              login: 'Anthonymcqueen21',
              name: 'Anthony Perez',
              id: 'MDQ6VXNlcjIzMjUzOTQx',
              isHireable: true,
              twitterUsername: 'some-twitter-username',
              url: 'https://github.com/Anthonymcqueen21',
              websiteUrl: 'https://website.com',
              email: 'anthonymcqueen29@gmail.com',
              bio: 'I got bored with programming, ethical hacking is more fun, challenging. And also more rewarding.',
              company: 'Hacker One | Bug Crowd |  Google Bug Bounty',
              location: 'Bakersfield Ca',
            },
            number: 21559,
            bodyText:
              'Hello fellow programmers i have been with Github for a year now and i feel i barely scratched the surface on what this site can do and offer. I made a few repositories showcasing my work general files and contributed on a few repositories but i want more.\nI have been told that Git is a very usfull tool for programmers can someone explain how to use Git and what can i contribute towards it. This may be a generic question but i would like the details if possible fellow members who are more experienced in the developement world.\nThank you.',
            title: 'Been with Github a year',
            id: 'MDEwOkRpc2N1c3Npb240MjQ3NjE5',
            url: 'https://github.com/orgs/community/discussions/21559',
            createdAt: '2017-11-01T19:21:30Z',
            comments: {
              totalCount: 5,
            },
            category: {
              id: 'DIC_kwDOEfmk4M4CQbSc',
              isAnswerable: true,
              name: 'New to GitHub',
              slug: 'new-to-github',
              emoji: ':new:',
              description: '',
            },
          },
          {
            author: {
              login: 'ghost',
              name: 'Deleted user',
              id: 'MDQ6VXNlcjEwMTM3',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/ghost',
              websiteUrl: null,
              email: '',
              bio: "Hi, I'm @ghost! I take the place of user accounts that have been deleted.\n:ghost:\n",
              company: null,
              location: 'Nothing to see here, move along.',
            },
            number: 21560,
            bodyText:
              'Hello!\nMy GitHub page has a small segement of code that writes a random quote from a list:\nvar quotes = [\n    "Quote 1",\n    "Quote 2"\n]\n// Quotes was altered from the original for the sake of this example\nvar qrandom = Math.floor(Math.random() * (quotes.length));\nfunction randomQuote()\n{\ndocument.getElementById(\'quote\').innerHTML = quotes[qrandom];\n}\n\nNow, could it be possible to grab the “var quotes list” from another JavaScript/JSON/etc. file? If so, how would the code exactly look like?\nThanks.',
            title: 'How to retrieve a JS variable list from another file?',
            id: 'MDEwOkRpc2N1c3Npb240MjQ3NjIx',
            url: 'https://github.com/orgs/community/discussions/21560',
            createdAt: '2017-11-01T13:31:09Z',
            comments: {
              totalCount: 2,
            },
            category: {
              id: 'MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyOTg5MjAz',
              isAnswerable: true,
              name: 'General',
              slug: 'general',
              emoji: ':octocat:',
              description: '',
            },
          },
          {
            author: {
              login: 'quinnlovescode',
              name: null,
              id: 'MDQ6VXNlcjMzMTA2MjIx',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/quinnlovescode',
              websiteUrl: null,
              email: '',
              bio: null,
              company: null,
              location: null,
            },
            number: 21561,
            bodyText:
              'I’m trying to put together a new blog and I found out about github pages from a friend and I think I want to use it for my blog. Can I do this? How do I use github pages for a blog?',
            title: 'Can I use GitHub Pages to host my blog?',
            id: 'MDEwOkRpc2N1c3Npb240MjQ3NjIy',
            url: 'https://github.com/orgs/community/discussions/21561',
            createdAt: '2017-10-25T23:09:06Z',
            comments: {
              totalCount: 2,
            },
            category: {
              id: 'MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyOTg5MjAz',
              isAnswerable: true,
              name: 'General',
              slug: 'general',
              emoji: ':octocat:',
              description: '',
            },
          },
          {
            author: {
              login: 'quinnlovescode',
              name: null,
              id: 'MDQ6VXNlcjMzMTA2MjIx',
              isHireable: false,
              twitterUsername: null,
              url: 'https://github.com/quinnlovescode',
              websiteUrl: null,
              email: '',
              bio: null,
              company: null,
              location: null,
            },
            number: 21562,
            bodyText:
              'I just created a new repo, and I made a typo and now I want to rename it. How do I do that?',
            title: 'How to do I rename my repo?',
            id: 'MDEwOkRpc2N1c3Npb240MjQ3NjIz',
            url: 'https://github.com/orgs/community/discussions/21562',
            createdAt: '2017-10-25T23:12:46Z',
            comments: {
              totalCount: 2,
            },
            category: {
              id: 'DIC_kwDOEfmk4M4CQbSc',
              isAnswerable: true,
              name: 'New to GitHub',
              slug: 'new-to-github',
              emoji: ':new:',
              description: '',
            },
          },
          {
            author: {
              login: 'AlMcKinlay',
              name: 'Al McKinlay',
              id: 'MDQ6VXNlcjIxNjI2NTc=',
              isHireable: false,
              twitterUsername: 'TheScotBot',
              url: 'https://github.com/AlMcKinlay',
              websiteUrl: null,
              email: '',
              bio: "I'm a software developer. \r\n\r\nIn my freetime, I spend time developing The Lounge and personal products. ",
              company: null,
              location: 'Edinburgh, Scotland',
            },
            number: 21563,
            bodyText:
              'I know GitHub supports Jekyll out of the box, and you can keep your source in the repository and it will automatically be compiled and deployed, but I was wondering if there was any support for other static site generators. I have recently started using hugo which I’m really enjoying using.',
            title: 'Using different static site generators',
            id: 'MDEwOkRpc2N1c3Npb240MjQ3NjI0',
            url: 'https://github.com/orgs/community/discussions/21563',
            createdAt: '2017-10-11T11:02:27Z',
            comments: {
              totalCount: 1,
            },
            category: {
              id: 'MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyOTg5MjAz',
              isAnswerable: true,
              name: 'General',
              slug: 'general',
              emoji: ':octocat:',
              description: '',
            },
          },
        ],
      },
    },
  },
}

export const mockDiscussionComments = {
  data: {
    repository: {
      discussion: {
        comments: {
          pageInfo: {
            hasPreviousPage: false,
            startCursor: 'Y3Vyc29yOnYyOpK5MjAyMi0wNy0xNlQwNDozODowNSswMjowMM4AMDlQ',
          },
          nodes: [
            {
              author: {
                login: 'snowflake-dev918',
                name: 'Louis Egan',
                id: 'U_kgDOBgbaQw',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/snowflake-dev918',
                websiteUrl: null,
                email: '',
                bio: 'Sr. Full Stack Developer',
                company: null,
                location: null,
              },
              bodyText:
                'Hey @Webmaster1125 . Nice to talk you.\nIf you implement this, you will get this badge.\nappear when you create a new PR and they are lost within 5 minutes of opening\nHope this will be help you.',
              url: 'https://github.com/community/community/discussions/20645#discussioncomment-3160400',
              id: 'DC_kwDOEfmk4M4AMDlQ',
              createdAt: '2022-07-16T02:38:05Z',
              isAnswer: true,
              replies: {
                nodes: [
                  {
                    author: {
                      login: 'The-Able',
                      name: 'Joao Souza',
                      id: 'U_kgDOBfdJ-w',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/The-Able',
                      websiteUrl: 'joaodavidmarketing@gmail.com',
                      email: '',
                      bio: 'Senior and Passionate Software Engineer',
                      company: null,
                      location: null,
                    },
                    bodyText: 'Thanks,',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3180353',
                    id: 'DC_kwDOEfmk4M4AMIdB',
                    createdAt: '2022-07-19T12:44:08Z',
                  },
                  {
                    author: {
                      login: 'The-Able',
                      name: 'Joao Souza',
                      id: 'U_kgDOBfdJ-w',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/The-Able',
                      websiteUrl: 'joaodavidmarketing@gmail.com',
                      email: '',
                      bio: 'Senior and Passionate Software Engineer',
                      company: null,
                      location: null,
                    },
                    bodyText: 'Thanks,',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3180354',
                    id: 'DC_kwDOEfmk4M4AMIdC',
                    createdAt: '2022-07-19T12:44:25Z',
                  },
                  {
                    author: {
                      login: 'MignonGakuba',
                      name: 'Mignon Gakuba',
                      id: 'MDQ6VXNlcjM2MjI4NTA4',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/MignonGakuba',
                      websiteUrl: null,
                      email: '',
                      bio: "Hi there, I'm Mignon Gakuba. 👋 🇷🇼  🇳🇱  ",
                      company: null,
                      location: 'Rotterdam',
                    },
                    bodyText: 'I dont follow',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3261766',
                    id: 'DC_kwDOEfmk4M4AMcVG',
                    createdAt: '2022-07-27T15:15:43Z',
                  },
                  {
                    author: {
                      login: 'nakatsinho',
                      name: 'Kelton M. Cumbe',
                      id: 'MDQ6VXNlcjU0ODMwNTQ0',
                      isHireable: true,
                      twitterUsername: 'nakatsinho',
                      url: 'https://github.com/nakatsinho',
                      websiteUrl: 'http://legocode.tech',
                      email: '',
                      bio: 'Software Developer | Mozambican Flutter Specialist | Bugs Solver',
                      company: '@champiermz @LegocodeMz ',
                      location: 'Maputo -  Mozambique',
                    },
                    bodyText: 'Oh... Great! Nice to know...',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3268538',
                    id: 'DC_kwDOEfmk4M4AMd-6',
                    createdAt: '2022-07-28T10:24:12Z',
                  },
                  {
                    author: {
                      login: 'Wazbat',
                      name: null,
                      id: 'MDQ6VXNlcjYyNTM4OTY=',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/Wazbat',
                      websiteUrl: null,
                      email: '',
                      bio: "Full Stack Engineer - TypeScript/JavaScript. I enjoy writing high quality code that's ready to delight customers",
                      company: null,
                      location: null,
                    },
                    bodyText: 'I dont follow\n\nCreate and merge a PR within the span of 5 minutes',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3276028',
                    id: 'DC_kwDOEfmk4M4AMfz8',
                    createdAt: '2022-07-29T00:37:07Z',
                  },
                  {
                    author: {
                      login: 'DrMadWill',
                      name: 'Nofel',
                      id: 'MDQ6VXNlcjg3NDc0NjMx',
                      isHireable: true,
                      twitterUsername: 'NofelSalahov',
                      url: 'https://github.com/DrMadWill',
                      websiteUrl: 'http://uversalfilo.site/',
                      email: '',
                      bio: 'I am a Full Stack Developer. I love learning code. Junior Developer.',
                      company: null,
                      location: 'Azerbaijan',
                    },
                    bodyText: 'If you implement this, you will get this badge.\n\nWhat is this ?',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3378161',
                    id: 'DC_kwDOEfmk4M4AM4vx',
                    createdAt: '2022-08-11T18:31:32Z',
                  },
                  {
                    author: {
                      login: 'Alexei567E',
                      name: null,
                      id: 'U_kgDOBpoxPA',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/Alexei567E',
                      websiteUrl: null,
                      email: '',
                      bio: '',
                      company: null,
                      location: null,
                    },
                    bodyText: '.github/workflows/browser-test.yml',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3439719',
                    id: 'DC_kwDOEfmk4M4ANHxn',
                    createdAt: '2022-08-21T05:50:10Z',
                  },
                ],
              },
              discussion: {
                url: 'https://github.com/orgs/community/discussions/20645',
                id: 'D_kwDOEfmk4M4AQGfY',
                title: 'How can I get Quickdraw badge??',
              },
            },
            {
              author: {
                login: 'Wazbat',
                name: null,
                id: 'MDQ6VXNlcjYyNTM4OTY=',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/Wazbat',
                websiteUrl: null,
                email: '',
                bio: "Full Stack Engineer - TypeScript/JavaScript. I enjoy writing high quality code that's ready to delight customers",
                company: null,
                location: null,
              },
              bodyText: 'Create and merge a PR within the span of 5 minutes',
              url: 'https://github.com/community/community/discussions/20645#discussioncomment-3276029',
              id: 'DC_kwDOEfmk4M4AMfz9',
              createdAt: '2022-07-29T00:37:12Z',
              isAnswer: false,
              replies: {
                nodes: [
                  {
                    author: {
                      login: 'markkdamm',
                      name: 'Mark Damm',
                      id: 'MDQ6VXNlcjczMzY3NTU3',
                      isHireable: false,
                      twitterUsername: 'mark__damm',
                      url: 'https://github.com/markkdamm',
                      websiteUrl: 'mark.axesoftwareai.com/notebook',
                      email: 'mark@axesoftwareai.com',
                      bio: 'Programmer, developer and designer, studying CS. 💻',
                      company: 'Looking for a job',
                      location: 'Malaga, Spain',
                    },
                    bodyText: "I did it yet I haven't received a badge",
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3373275',
                    id: 'DC_kwDOEfmk4M4AM3jb',
                    createdAt: '2022-08-11T09:39:07Z',
                  },
                  {
                    author: {
                      login: 'Wazbat',
                      name: null,
                      id: 'MDQ6VXNlcjYyNTM4OTY=',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/Wazbat',
                      websiteUrl: null,
                      email: '',
                      bio: "Full Stack Engineer - TypeScript/JavaScript. I enjoy writing high quality code that's ready to delight customers",
                      company: null,
                      location: null,
                    },
                    bodyText:
                      "I did it yet I haven't received a badge\n\nI looked through your history and found one PR you made around the same time as this comment, rohya8/mean-stack-interview-questions#2\nThe PR was not merged, only created. It must be created and merged in a 5 minute window",
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3378044',
                    id: 'DC_kwDOEfmk4M4AM4t8',
                    createdAt: '2022-08-11T18:14:32Z',
                  },
                ],
              },
              discussion: {
                url: 'https://github.com/orgs/community/discussions/20645',
                id: 'D_kwDOEfmk4M4AQGfY',
                title: 'How can I get Quickdraw badge??',
              },
            },
            {
              author: {
                login: 'dennis1125',
                name: 'Dennis Stephens',
                id: 'U_kgDOBhwAtA',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/dennis1125',
                websiteUrl: null,
                email: 'mickeyglass.1125@gmail.com',
                bio: 'Full stack & Blockchain Developer',
                company: 'https://github.com/Cartezi',
                location: null,
              },
              bodyText:
                "I will make you let know.\n…\nOn Thu, Aug 11, 2022 at 12:39 PM Mark Damm ***@***.***> wrote:\n I did it yet I haven't received a badge\n\n —\n Reply to this email directly, view it on GitHub\n <https://github.com/orgs/community/discussions/20645#discussioncomment-3373275>,\n or unsubscribe\n <https://github.com/notifications/unsubscribe-auth/AYOABNA73A7TFNVN5HXOE2TVYTC4PANCNFSM53XKHW5Q>\n .\n You are receiving this because you were mentioned.Message ID:\n ***@***.***>",
              url: 'https://github.com/community/community/discussions/20645#discussioncomment-3374258',
              id: 'DC_kwDOEfmk4M4AM3yy',
              createdAt: '2022-08-11T12:46:52Z',
              isAnswer: false,
              replies: {
                nodes: [],
              },
              discussion: {
                url: 'https://github.com/orgs/community/discussions/20645',
                id: 'D_kwDOEfmk4M4AQGfY',
                title: 'How can I get Quickdraw badge??',
              },
            },
            {
              author: {
                login: 'hafizmp',
                name: 'CodeKofy',
                id: 'U_kgDOBdswSA',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/hafizmp',
                websiteUrl: null,
                email: '',
                bio: 'MERN stack Developer',
                company: null,
                location: 'Kerala, India',
              },
              bodyText: 'Try to Close an issue or a pull request within 5 min of opening',
              url: 'https://github.com/community/community/discussions/20645#discussioncomment-3396954',
              id: 'DC_kwDOEfmk4M4AM9Va',
              createdAt: '2022-08-15T09:38:10Z',
              isAnswer: false,
              replies: {
                nodes: [],
              },
              discussion: {
                url: 'https://github.com/orgs/community/discussions/20645',
                id: 'D_kwDOEfmk4M4AQGfY',
                title: 'How can I get Quickdraw badge??',
              },
            },
            {
              author: {
                login: 'Potential17',
                name: 'Shashwat Pandey',
                id: 'MDQ6VXNlcjQ5ODE0MjA1',
                isHireable: false,
                twitterUsername: null,
                url: 'https://github.com/Potential17',
                websiteUrl: null,
                email: 'cool17shashwat@gmail.com',
                bio: '"On the way"',
                company: null,
                location: 'Bengaluru',
              },
              bodyText:
                "I didn't get the the Quickdraw Badge even after my PR was merged within 5 mins of opening!",
              url: 'https://github.com/community/community/discussions/20645#discussioncomment-3436055',
              id: 'DC_kwDOEfmk4M4ANG4X',
              createdAt: '2022-08-20T06:40:06Z',
              isAnswer: false,
              replies: {
                nodes: [
                  {
                    author: {
                      login: 'hafizmp',
                      name: 'CodeKofy',
                      id: 'U_kgDOBdswSA',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/hafizmp',
                      websiteUrl: null,
                      email: '',
                      bio: 'MERN stack Developer',
                      company: null,
                      location: 'Kerala, India',
                    },
                    bodyText:
                      'You have to make a pull request and the repo owner should be pulled and merge the request within a span of 5 minutes.\n(Remember that you must ensure that the repo is forked to your profile and cloned)',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3436083',
                    id: 'DC_kwDOEfmk4M4ANG4z',
                    createdAt: '2022-08-20T06:55:30Z',
                  },
                  {
                    author: {
                      login: 'Potential17',
                      name: 'Shashwat Pandey',
                      id: 'MDQ6VXNlcjQ5ODE0MjA1',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/Potential17',
                      websiteUrl: null,
                      email: 'cool17shashwat@gmail.com',
                      bio: '"On the way"',
                      company: null,
                      location: 'Bengaluru',
                    },
                    bodyText: "I have done that but still didn't get.",
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3436116',
                    id: 'DC_kwDOEfmk4M4ANG5U',
                    createdAt: '2022-08-20T07:09:59Z',
                  },
                  {
                    author: {
                      login: 'HAMMAS-SALEEM',
                      name: 'HAMMAS BIN SALEEM',
                      id: 'U_kgDOBYuq_w',
                      isHireable: true,
                      twitterUsername: 'HammasSaleem4',
                      url: 'https://github.com/HAMMAS-SALEEM',
                      websiteUrl: 'https://hammas-portfolio.netlify.app/',
                      email: 'hammassaleem376@gmail.com',
                      bio: "Hello | Hammas here | Aspiring Full-stack Developer | Inshallah System Evolver.\r\nI'm open to new job opportunities.",
                      company: 'Looking for job opportunities',
                      location: 'Faisalabad, Pakistan',
                    },
                    bodyText:
                      'I guess there is a deadline for each badge and for quick draw badge we have crossed the deadline.',
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3439490',
                    id: 'DC_kwDOEfmk4M4ANHuC',
                    createdAt: '2022-08-21T03:25:31Z',
                  },
                  {
                    author: {
                      login: 'Wazbat',
                      name: null,
                      id: 'MDQ6VXNlcjYyNTM4OTY=',
                      isHireable: false,
                      twitterUsername: null,
                      url: 'https://github.com/Wazbat',
                      websiteUrl: null,
                      email: '',
                      bio: "Full Stack Engineer - TypeScript/JavaScript. I enjoy writing high quality code that's ready to delight customers",
                      company: null,
                      location: null,
                    },
                    bodyText:
                      "It doesn't have to be a fork. I did it in a private org repo directly. No fork involved",
                    url: 'https://github.com/community/community/discussions/20645#discussioncomment-3440674',
                    id: 'DC_kwDOEfmk4M4ANIAi',
                    createdAt: '2022-08-21T12:01:41Z',
                  },
                ],
              },
              discussion: {
                url: 'https://github.com/orgs/community/discussions/20645',
                id: 'D_kwDOEfmk4M4AQGfY',
                title: 'How can I get Quickdraw badge??',
              },
            },
          ],
        },
      },
    },
  },
}
