FROM node:16-alpine

WORKDIR /usr/crowd/conversations

COPY package-lock.json package.json ./
RUN npm ci

COPY app.vue nuxt.config.ts tailwind.config.js tsconfig.json ./

COPY ./assets ./assets
COPY ./components ./components
COPY ./composables ./composables
COPY ./helpers ./helpers
COPY ./pages ./pages
COPY ./public ./public
COPY ./sample-data ./sample-data
COPY ./server ./server