CREATE TABLE IF NOT EXISTS 'activities' (
  id UUID,
  type VARCHAR,
  timestamp TIMESTAMP,
  platform SYMBOL CAPACITY 30,
  isContribution BOOLEAN,
  score INT,
  sourceId VARCHAR,
  createdAt TIMESTAMP,
  updatedAt TIMESTAMP,
  deletedAt TIMESTAMP,
  memberId UUID,
  parentId UUID,
  tenantId SYMBOL,
  createdById UUID,
  updatedById UUID,
  sourceParentId VARCHAR,
  conversationId UUID,
  attributes VARCHAR,
  title VARCHAR,
  body VARCHAR,
  channel VARCHAR,
  url VARCHAR,
  username VARCHAR,
  objectMemberId UUID,
  objectMemberUsername VARCHAR,
  segmentId SYMBOL,
  organizationId UUID,

  sentimentLabel VARCHAR,
  sentimentScore INT,
  sentimentScoreMixed FLOAT,
  sentimentScoreNeutral FLOAT,
  sentimentScoreNegative FLOAT,
  sentimentScorePositive FLOAT,

  member_isBot BOOLEAN,
  member_isTeamMember BOOLEAN,

  gitIsMainBranch BOOLEAN,
  gitIsIndirectFork BOOLEAN,
  gitInsertions INT,
  gitDeletions INT
) TIMESTAMP (timestamp) PARTITION BY DAY WAL;

CREATE TABLE IF NOT EXISTS 'conversations' (
  id UUID,
  title VARCHAR,
  slug VARCHAR,
  published BOOLEAN,
  timestamp TIMESTAMP,
  createdAt TIMESTAMP,
  updatedAt TIMESTAMP,
  deletedAt TIMESTAMP,
  tenantId SYMBOL,
  segmentId SYMBOL,
  createdById UUID,
  updatedById UUID
) TIMESTAMP (timestamp) PARTITION BY DAY WAL;
