/**
 * A set of known bot handles that are not easily caught by the generic regex patterns.
 * This list handles exceptions with unique names or non-standard formats.
 */
export const knownBots = new Set([
  // GitHub bots
  'allcontributors',
  'better-code-hub',
  'bors',
  'bors-servo',
  'brewtestbot',
  'codeclimate',
  'codepilot',
  'coderabbit',
  'copilot',
  'dependabot',
  'easycla',
  'fabbot',
  'facebook-github-bot',
  'github-merge-queue',
  'goreleaserbot',
  'harness-ci',
  'hashibot',
  'homebrewbumpbot',
  'homu',
  'jenkins',
  'mergify',
  'msftbot',
  'opentelemetrybot',
  'pep8speaks',
  'prombot',
  'pullrequest',
  'renovate',
  'reviewdog',
  'rust-highfive',
  'rustbot',
  'scala-steward',
  'scrutinizer-auto-fixer',
  'sonatype-lift',
  'sphinx-bot',
  'teamcity',
  'tensorflower',
  'web-flow',
  'weblate',
  'zuul',

  // Service automation bots
  'codecov',
  'deepsource',
  'gitguardian',
  'snyk',
  'whitesource',

  // Discord Bots
  'arcane',
  'craig',
  'dankmemer',
  'dyno',
  'fredboat',
  'groovy',
  'helper.gg',
  'idlerpg',
  'maki',
  'mee6',
  'mudae',
  'notsobot',
  'rythm',
  'serverstats',
  'tatsu',
  'tickettool',
  'unbelievaboat',
  'yagpdb.xyz',

  // Reddit Bots
  'apollo',
  'automoderator',
  'common-misspelling-bot',
  'remindmebot',
  'totesmessenger',
  'vredditdownloader',
])
