components:
  schemas:
    MemberType:
      type: string
      enum:
        - member
    MemberScore:
      type: integer
      minimum: -1
      maximum: 10
    MemberSort:
      type: string
      enum:
        - activitiesCount_ASC
        - activitiesCount_DESC
        - score_ASC
        - score_ASC
        - joinedAt_ASC
        - joinedAt_DESC
        - createdAt_ASC
        - createdAt_DESC
        - organisation_ASC
        - organisation_DESC
        - location_ASC
        - location_DESC
    ActivitySort:
      type: string
      enum:
        - timestamp_DESC
        - timestamp_ASC
        - createdAt_DESC
        - createdAt_ASC
        - score_DESC
        - score_ASC
        - type_DESC
        - type_ASC
        - platform_DESC
        - platform_ASC
        - createdBy_DESC
        - createdBy_ASC
    ConversationSort:
      type: string
      enum:
        - createdAt_DESC
        - createdAt_ASC
        - activityCount_DESC
        - activityCount_ASC
        - platform_DESC
        - platform_ASC
        - channel_DESC
        - channel_ASC
        - createdBy_DESC
        - createdBy_ASC
    TagSort:
      type: string
      enum:
        - name_ASC
        - name_DESC
        - createdAt_DESC
        - createdAt_ASC

    MemberAttributeSettingsSort:
      type: string
      enum:
        - label_ASC
        - label_DESC
        - type_ASC
        - type_DESC
        - createdAt_DESC
        - createdAt_ASC
