#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    MSYS_NT*)   machine=Windows;;
    *)          machine="UNKNOWN:${unameOut}"
esac


case "$machine" in
    Windows)
      source venv-crowd/Scripts/activate
      ;;
    MinGw)
      source venv-crowd/Scripts/activate
      ;;
    *)
      source venv-crowd/bin/activate
      ;;
esac

pytest
