FROM node:16-alpine

RUN apk add --update --no-cache bash python3 build-base micro git ncurses && ln -sf python3 /usr/bin/python && python3 -m ensurepip && pip3 install --no-cache --upgrade pip setuptools && corepack enable

WORKDIR /usr/crowd/app

RUN git clone https://github.com/CrowdDotDev/crowd.dev.git && cd crowd.dev && pnpm i --frozen-lockfile

WORKDIR /usr/crowd/app/crowd.dev