FROM node:16-alpine

RUN apk add --update --no-cache bash

WORKDIR /usr/crowd/app

COPY ./services/scripts ./services/scripts
COPY ./services/libs/ ./services/libs/
RUN cd services/scripts && ./install_lib_packages.sh

COPY ./services/apps/data_sink_worker/package.json ./services/apps/data_sink_worker/package-lock.json ./services/apps/data_sink_worker/tsconfig.json  ./services/apps/data_sink_worker/
COPY ./services/apps/data_sink_worker/config ./services/apps/data_sink_worker/config
COPY ./services/apps/data_sink_worker/src ./services/apps/data_sink_worker/src
RUN cd services/apps/data_sink_worker && npm ci

RUN npm cache clean --force
