FROM node:20-alpine

RUN npm install -g corepack@latest && corepack enable pnpm && corepack use pnpm@9.15.0

WORKDIR /usr/crowd/app

RUN apk add --no-cache nano git python3 py3-pip make build-base && rm -rf /var/cache/apk/* && git clone https://github.com/CrowdDotDev/crowd.dev.git && cd crowd.dev && pnpm i --frozen-lockfile

WORKDIR /usr/crowd/app/crowd.dev