FROM node:16-alpine

RUN apk add --update --no-cache bash

WORKDIR /usr/crowd/app

COPY ./services/scripts ./services/scripts
COPY ./services/libs/ ./services/libs/
RUN cd services/scripts && ./install_lib_packages.sh

COPY ./services/apps/search_sync_api/package.json ./services/apps/search_sync_api/package-lock.json ./services/apps/search_sync_api/tsconfig.json  ./services/apps/search_sync_api/
COPY ./services/apps/search_sync_api/config ./services/apps/search_sync_api/config
COPY ./services/apps/search_sync_api/src ./services/apps/search_sync_api/src

RUN cd services/apps/search_sync_api && npm ci

RUN npm cache clean --force
