FROM node:16-alpine as builder

WORKDIR /usr/crowd/app
RUN corepack enable && apk add --update --no-cache python3 build-base && ln -sf python3 /usr/bin/python && python3 -m ensurepip && pip3 install --no-cache --upgrade pip setuptools

COPY ./pnpm-workspace.yaml ./pnpm-lock.yaml ./
COPY ./services ./services
RUN pnpm i --frozen-lockfile

FROM node:16-alpine as runner

WORKDIR /usr/crowd/app
RUN corepack enable

COPY --from=builder /usr/crowd/app/node_modules ./node_modules
COPY --from=builder /usr/crowd/app/services/libs ./services/libs
COPY --from=builder /usr/crowd/app/services/apps/integration_sync_worker/ ./services/apps/integration_sync_worker
