FROM node:20-alpine as builder

WORKDIR /usr/crowd/app
RUN corepack enable 
#RUN apk add --update --no-cache python3 build-base && ln -sf python3 /usr/bin/python && python3 -m ensurepip && pip3 install --no-cache --upgrade pip setuptools
RUN apk add --no-cache python3 py3-pip build-base
RUN if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi

COPY ./pnpm-workspace.yaml ./pnpm-lock.yaml ./
COPY ./services ./services
RUN pnpm i --frozen-lockfile

FROM node:20-bookworm-slim as runner

WORKDIR /usr/crowd/app
RUN corepack enable && apt update && apt install -y ca-certificates --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/crowd/app/node_modules ./node_modules
COPY --from=builder /usr/crowd/app/services/libs ./services/libs
COPY --from=builder /usr/crowd/app/services/archetypes/ ./services/archetypes
COPY --from=builder /usr/crowd/app/services/apps/entity_merging_worker/ ./services/apps/entity_merging_worker
