FROM node:16-bookworm as builder

WORKDIR /usr/crowd/app

COPY ./services ./services
RUN cd services/scripts && ./install_lib_packages.sh &&  ./install_app_packages.sh

FROM node:16-bookworm as runner

WORKDIR /usr/crowd/app

COPY --from=builder /usr/crowd/app/services/libs ./services/libs
COPY --from=builder /usr/crowd/app/services/archetypes ./services/archetypes
COPY --from=builder /usr/crowd/app/services/apps/emails_worker ./services/apps/emails_worker