FROM node:16-alpine as builder

WORKDIR /usr/crowd/app
RUN corepack enable

COPY ./pnpm-workspace.yaml ./pnpm-lock.yaml ./
COPY ./services ./services
RUN pnpm i --frozen-lockfile

FROM node:16-alpine as runner

WORKDIR /usr/crowd/app
RUN corepack enable

COPY --from=builder /usr/crowd/app/node_modules ./node_modules
COPY --from=builder /usr/crowd/app/services/libs ./services/libs
COPY --from=builder /usr/crowd/app/services/apps/integration_run_worker/ ./services/apps/integration_run_worker