name: Crowd Slack notifier
description: Triggers a message to Crowd.dev slack channels

inputs:
  message:
    description: Which message to send?
    required: true

runs:
  using: composite
  steps:
    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
        SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
        SLACK_USERNAME: Crowd.dev Deploy Notifier
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_TITLE: Deploy successful!
        SLACK_MESSAGE: ${{ inputs.message }}
