export enum Platform {
    GITHUB = 'github',
    DISCORD = 'discord',
    HACKER_NEWS = 'hackernews',
    LINKEDIN = 'linkedin',
    TWITTER = 'twitter',
    SLACK = 'slack',
    DEVTO = 'devto',
    REDDIT = 'reddit',
    STACK_OVERFLOW = 'stackOverflow',
    DISCOURSE = 'discourse',
    HUBSPOT = 'hubspot',
    GIT = 'git',
    GROUPS_IO = 'groupsio',
    CUSTOM = 'custom',
    EMAIL = 'email',
    EMAILS = 'emails',
    PHONE_NUMBERS = 'phoneNumbers',
    CRUNCHBASE = 'crunchbase',
}
