export enum Platform {
    ALL = 'all',
    GITHUB = 'github',
    DISCORD = 'discord',
    HACKER_NEWS = 'hackernews',
    LINKEDIN = 'linkedin',
    TWITTER = 'twitter',
    SLACK = 'slack',
    DEVTO = 'devto',
    INTEGRATION = 'integration',
    REDDIT = 'reddit',
    STACK_OVERFLOW = 'stackOverflow',
    DISCOURSE = 'discourse',
    HUBSPOT = 'hubspot',
    GIT = 'git',
    GROUPS_IO = 'groupsio',
    CUSTOM = 'custom',
    ENRICHMENT = 'enrichment',
    EMAIL = 'email',
    EMAILS = 'emails',
    PHONE_NUMBERS = 'phoneNumbers',
    CRUNCHBASE = 'crunchbase',
    CONFLUENCE = 'confluence',
    GITLAB = 'gitlab',
    JIRA = 'jira',
    GITHUB_NANGO = 'github-nango',
    GERRIT = 'gerrit',
}
