version: '3.1'

services:
  unleash-db:
    image: postgres:13.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=crowd-unleash
    ports:
      - 5431:5432
    volumes:
      - pgdata-unleash-dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'crowd-unleash']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - crowd-bridge

  # default user credentials: admin:unleash4all
  unleash:
    image: unleashorg/unleash-server:latest
    restart: unless-stopped
    depends_on:
      unleash-db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=unleash-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=crowd-unleash
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_SSL=false
    ports:
      - '4242:4242'
    networks:
      - crowd-bridge

networks:
  crowd-bridge:
    external: true

volumes:
  pgdata-unleash-dev:
