services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    command: -c 'max_connections=300' -c 'wal_level=logical' -c 'max_replication_slots=11' -c 'max_replication_slots=15'
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=crowd-web
    ports:
      - 5432:5432
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ./scaffold/sequin/postgres-docker-entrypoint-initdb.d/create-sequin-database.sql:/docker-entrypoint-initdb.d/create-sequin-database.sql
    shm_size: 1gb
    networks:
      - crowd-bridge

  product:
    image: postgres:14-alpine
    restart: unless-stopped
    command: -c 'max_connections=300'
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=product-db
    ports:
      - 5433:5432
    volumes:
      - pgdata-product-dev:/var/lib/postgresql/data
    shm_size: 1gb
    networks:
      - crowd-bridge

  open-search:
    image: opensearchproject/opensearch:2.7.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'DISABLE_INSTALL_DEMO_CONFIG=true'
      - 'DISABLE_SECURITY_PLUGIN=true'
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-dev:/usr/share/opensearch/data
    networks:
      - crowd-bridge

  # uncomment to enable dashboard
  # open-search-dashboard:
  #   image: opensearchproject/opensearch-dashboards:2.7.0
  #   restart: unless-stopped
  #   environment:
  #     - 'OPENSEARCH_HOSTS=["http://open-search:9200"]'
  #     - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - crowd-bridge

  s3:
    image: scireum/s3-ninja:8.0.0
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - s3-dev:/home/sirius/data
    networks:
      - crowd-bridge

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    volumes:
      - ./scaffold/nginx/templates:/etc/nginx/templates
      - ./scaffold/nginx/ssl:/etc/nginx/ssl
    ports:
      - '443:443'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    networks:
      - crowd-bridge
    profiles:
      - nginx

  redis:
    build:
      context: scaffold/redis
    command: 'redis-server /redis.conf --requirepass crowdtest'
    restart: unless-stopped
    volumes:
      - redis-dev:/data
    ports:
      - 6379:6379
    networks:
      - crowd-bridge

  nango:
    image: nangohq/nango-server:0.9.0
    restart: unless-stopped
    environment:
      - NANGO_DB_HOST=db
      - NANGO_DB_PORT=5432
      - NANGO_DB_NAME=crowd-web
      - NANGO_DB_USER=postgres
      - NANGO_DB_PASSWORD=example
      - NANGO_SECRET_KEY=424242
      - NANGO_CALLBACK_URL=http://localhost:3003/oauth/callback
      - NANGO_SERVER_URL=http://localhost:3003
      - SERVER_PORT=3003
    ports:
      - '3003:3003'
    networks:
      - crowd-bridge

  kafka:
    image: bitnamilegacy/kafka:3.8.1
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/opt/bitnami/kafka/data
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
      - '9093:9093'
      - '9094:9094'
    networks:
      - crowd-bridge

  kafka-connect:
    container_name: kafka-connect
    build:
      context: scaffold/kafka-connect
    entrypoint: ['/bin/sh', '-c', '/configure-tinybird-sink.sh']
    restart: unless-stopped
    volumes:
      - kafka-connect-dev:/storage
      - ./scaffold/kafka-connect/configure-tinybird-sink.sh:/configure-tinybird-sink.sh
      - ./scaffold/kafka-connect/worker-local.properties:/etc/kafka-connect/worker-local.properties
      - ./scaffold/kafka-connect/console-local-sink.properties:/etc/kafka-connect/console-local-sink.properties
      - ./scaffold/kafka-connect/tinybird-local-sink.properties:/etc/kafka-connect/tinybird-local-sink.properties
    depends_on:
      - tinybird
    networks:
      - crowd-bridge

  temporal:
    build:
      context: scaffold/temporal
    restart: unless-stopped
    ports:
      - '7233:7233'
      - '8233:8233'
    networks:
      - crowd-bridge

  tinybird:
    container_name: tinybird-local
    image: tinybirdco/tinybird-local:latest
    platform: 'linux/amd64'
    environment:
      - COMPATIBILITY_MODE=1 # <— force Classic version
    ports:
      - '80:80'
      - '7181:7181'
    networks:
      - crowd-bridge

networks:
  crowd-bridge:
    external: true

volumes:
  pgdata-dev:
  pgdata-product-dev:
  opensearch-dev:
  s3-dev:
  redis-dev:
  kafka-connect-dev:
  sequin-dev:
  tinybird-data:
