version: '3.1'

services:
  cubejs:
    image: cubejs/cube
    ports:
      - '4000:4000'
      - '3001:3000'
    volumes:
      - '../backend/src/cubejs:/cube/conf'
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=db
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=crowd-web
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_PASS=example
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=137ea167812145c6d77452a58d7dd29b
      - CUBEJS_EXTERNAL_DEFAULT=true
      - CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
    networks:
      - crowd-bridge

  db:
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=crowd-web
    ports:
      - 5432:5432
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - crowd-bridge

  search-engine:
    image: getmeili/meilisearch:v0.27.2
    ports:
      - 7700:7700
    volumes:
      - search-dev:/data.ms
    networks:
      - crowd-bridge

  s3:
    image: scireum/s3-ninja:8.0.0
    ports:
      - 9000:9000
    volumes:
      - s3-dev:/home/sirius/data
    networks:
      - crowd-bridge

  sqs:
    build:
      context: scaffold/sqs
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - crowd-bridge

  nginx:
    image: nginx:alpine
    volumes:
      - ./scaffold/nginx/templates:/etc/nginx/templates
      - ./scaffold/nginx/ssl:/etc/nginx/ssl
    ports:
      - '443:443'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    networks:
      - crowd-bridge

networks:
  crowd-bridge:
    external: true

volumes:
  pgdata-dev:
  search-dev:
  s3-dev:
