services:
  sequin:
    image: sequin/sequin:latest
    restart: unless-stopped
    ports:
      - '7376:7376'
    environment:
      - PG_HOSTNAME=db
      - PG_DATABASE=sequin
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=example
      - PG_POOL_SIZE=10
      - SECRET_KEY_BASE=${CROWD_SEQUIN_SECRET_KEY_BASE:-WyPLiGs0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If}
      - VAULT_KEY=${CROWD_SEQUIN_VAULT_KEY:-2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=}
      - REDIS_URL=redis://default:crowdtest@redis:6379
      - SERVER_HOST=${CROWD_SEQUIN_SERVER_HOST:-localhost}
      - SERVER_PORT=${CROWD_SEQUIN_SERVER_PORT:-7376}
      - CONFIG_FILE_PATH=/config/sequin.yml
    volumes:
      - ./scaffold/sequin.yml:/config/sequin.yml
    depends_on:
      - db
      - redis
      - kafka
    networks:
      - crowd-bridge
    profiles:
      - insights
