name: API docs

on:
  release:
    types: [released]
jobs:
  tests-main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install root dependencies
        run: corepack enable && pnpm i --frozen-lockfile

      - name: Run docs script
        working-directory: ./backend
        run: pnpm run docs -- ${{ secrets.README_API_KEY }}
