name: API docs

on:
  release:
      types: [released]
jobs:
  tests-main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps: 
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Install root dependencies
          run:  npm ci
        
        - name: Run docs script
          working-directory: ./backend
          run: npm run docs -- ${{ secrets.README_API_KEY }}
