# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
name: Jira PR Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-jira-key:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Jira issue key in PR title
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            console.log(`PR Title: ${prTitle}`);
            
            // Regex to match Jira issue keys (CDP-123 format)
            // Supports conventional commits format: type(CDP-123): description
            const jiraKeyRegex = /\b[A-Z]+-\d+\b/;
            
            if (!jiraKeyRegex.test(prTitle)) {
              const warningMessage = `⚠️ **Jira Issue Key Missing**
              
              Your PR title doesn't contain a Jira issue key. Consider adding it for better traceability.
              
              **Examples:**
              - \`feat: add user authentication [PROJ-123]\`
              - \`fix(PROJ-123): resolve login issue [PROJ-456]\`
              
              This is a reminder only - you can still merge this PR.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: warningMessage
              });
              
              // Set status but don't fail the check
              github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: 'pending',
                target_url: 'https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/actions',
                description: 'Jira issue key not found in PR title',
                context: 'Jira PR Validation'
              });
            } else {
              const match = prTitle.match(jiraKeyRegex);
              console.log(`✅ Found Jira issue key: ${match[0]}`);
              
              github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: 'success',
                target_url: 'https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/actions',
                description: `Jira issue key found: ${match[0]}`,
                context: 'Jira PR Validation'
              });
            }